### ISSUE TITLE
أنا سأصاب بالجنون، الرجاء مساعدة شخص ما، فأنا عالق في الغابة

### ISSUE THREAD

**Issue by Hek3er** [Hek3er/Cube3d#1]
![371729439-832065df-5f86-4554-bfdb-43a86902401c](https://github.com/user-attachments/assets/1e68d103-039d-4672-bc35-f03005e9d9b5)

**Comment by sel-jett** [comment]
<img width="2062" alt="Screen Shot 2024-10-22 at 9 08 53 AM" src="https://github.com/user-attachments/assets/fa383fcc-c56f-4bdf-854a-5382a94a7001">

**Comment by Hek3er** [comment]
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
